name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download and Install SpotBugs
      run: |
        curl -L https://github.com/spotbugs/spotbugs/releases/download/4.5.3/spotbugs-4.5.3.tgz -o spotbugs.tgz
        tar -xzf spotbugs.tgz
        sudo mv spotbugs-4.5.3 /opt/spotbugs
        sudo ln -s /opt/spotbugs/bin/spotbugs /usr/local/bin/spotbugs
        sudo chmod +x /opt/spotbugs/bin/spotbugs

    - name: Clean previous builds
      run: find . -name "*.class" -type f -delete
      
    - name: Compile Java
      run: javac Ejercicio3/*.java

    - name: Run SpotBugs
      run: spotbugs -textui -effort:max -high Ejercicio3/*.class

    - name: Run Java
      run: java -cp Ejercicio3 Ejercicio3.SistemaDeInventario

    - name: Download and Install OWASP Dependency-Check
      run: |
        curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v6.1.6/dependency-check-6.1.6-release.zip -o dependency-check.zip
        unzip dependency-check.zip
        sudo mv dependency-check /opt/dependency-check
        sudo chmod +x /opt/dependency-check/bin/dependency-check.sh
        sudo ln -s /opt/dependency-check/bin/dependency-check.sh /usr/local/bin/dependency-check.sh

    - name: Run OWASP Dependency-Check
      run: dependency-check.sh --project Pez --scan . --disableAssembly
